version: '3.8'
services:
  harvest-sheet:
    image: harvest-sheet:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./output:/app/output # Adjust if your script writes output files
    restart: unless-stopped
