name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Google Client ID
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
        run: |
          # Verify secret is available
          if [ -z "$GOOGLE_CLIENT_ID" ]; then
            echo "❌ ERROR: OAUTH_CLIENT_ID secret is not set!"
            exit 1
          fi

          echo "✅ Secret found (length: ${#GOOGLE_CLIENT_ID})"

          # Replace placeholder with actual Client ID from secrets
          sed -i "s|YOUR_GOOGLE_CLIENT_ID|${GOOGLE_CLIENT_ID}|g" docs/app.js
          sed -i "s|YOUR_GOOGLE_CLIENT_ID|${GOOGLE_CLIENT_ID}|g" docs/index.html

          # Verify replacement worked
          if grep -q "YOUR_GOOGLE_CLIENT_ID" docs/app.js; then
            echo "❌ ERROR: Replacement failed in app.js"
            exit 1
          fi

          if grep -q "YOUR_GOOGLE_CLIENT_ID" docs/index.html; then
            echo "❌ ERROR: Replacement failed in index.html"
            exit 1
          fi

          echo "✅ Successfully injected Google Client ID into deployment files"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
